# [[approved]]
# word = "example word"
# pos = "noun"

# [[not_approved]]
# word = "bad word"
# pos = "noun"
# alternatives = [{ word = "example word" }]

[[approved]]
word = "actuator"
pos = "noun"

[[not_approved]]
word = "servo control unit"
pos = "noun"
alternatives = [{ word = "actuator" }]

[[not_approved]]
word = "control unit"
pos = "noun"
alternatives = [{ word = "actuator" }]

[[approved]]
word = "touchscreen"
pos = "noun"
