[package]
name = "goodwrite-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "goodwrite"
path = "src/main.rs"

[dependencies]
goodwrite-core.workspace = true
goodwrite-extract.workspace = true
goodwrite-tokenize.workspace = true
goodwrite-asd-ste100.workspace = true
goodwrite-ears.workspace = true
goodwrite-glossary.workspace = true
clap.workspace = true
glob.workspace = true
miette.workspace = true
owo-colors.workspace = true
serde_json.workspace = true
similar.workspace = true
thiserror.workspace = true
indicatif.workspace = true
