[package]
name = "goodwrite-extract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
goodwrite-core.workspace = true
pulldown-cmark.workspace = true
typst-syntax.workspace = true
thiserror.workspace = true
regex.workspace = true
