[profile]
name = "asd-ste100"

[rules]
"asd-ste100/unapproved-word" = "error"
"asd-ste100/approved-word-pos-mismatch" = "warn"
"asd-ste100/ambiguous-pos" = "warn"
"asd-ste100/alternative-pos-mismatch" = "warn"
"asd-ste100/approved-meaning" = "info"
"asd-ste100/approved-word-form" = "error"
"asd-ste100/technical-noun-category" = "info"
"asd-ste100/non-approved-as-technical-noun" = "info"
"asd-ste100/technical-noun-as-verb" = "warn"
"asd-ste100/company-approved-technical-noun" = "info"
"asd-ste100/technical-noun-length" = "warn"
"asd-ste100/no-jargon-technical-noun" = "warn"
"asd-ste100/consistent-technical-noun" = "warn"
"asd-ste100/technical-verb-category" = "info"
"asd-ste100/technical-verb-as-noun" = "warn"
"asd-ste100/american-spelling" = "error"
"asd-ste100/multi-word-noun-length" = "warn"
"asd-ste100/abbreviation-first-use" = "warn"
"asd-ste100/verb-forms" = "warn"
"asd-ste100/approved-tenses" = "warn"
"asd-ste100/past-participle-as-adjective" = "warn"
"asd-ste100/no-complex-auxiliary" = "warn"
"asd-ste100/ing-form-restriction" = "warn"
"asd-ste100/nominalization" = "warn"
"asd-ste100/contractions" = "error"
"asd-ste100/use-vertical-lists" = "info"
"asd-ste100/connecting-words" = "info"
"asd-ste100/articles-before-nouns" = "warn"
"asd-ste100/sentence-length-procedural" = "error"
"asd-ste100/sentence-length-descriptive" = "error"
"asd-ste100/one-instruction-per-sentence" = "warn"
"asd-ste100/imperative-procedural" = "warn"
"asd-ste100/condition-before-command" = "warn"
"asd-ste100/note-no-imperative" = "warn"
"asd-ste100/one-subject-per-sentence" = "info"
"asd-ste100/key-words-structure" = "info"
"asd-ste100/paragraph-related-info" = "info"
"asd-ste100/one-topic-per-paragraph" = "info"
"asd-ste100/max-sentences-paragraph" = "warn"
"asd-ste100/safety-risk-level" = "warn"
"asd-ste100/safety-start-command-or-condition" = "warn"
"asd-ste100/safety-risk-explanation" = "warn"
"asd-ste100/passive-voice" = "warn"
"asd-ste100/semicolons" = "error"
"asd-ste100/hyphen-related-words" = "info"
"asd-ste100/parentheses-usage" = "info"
"asd-ste100/gr-that-which" = "warn"
"asd-ste100/gr-ambiguous-with" = "warn"
"asd-ste100/gr-pronoun-antecedent" = "warn"
"asd-ste100/gr-this-referent" = "warn"
"asd-ste100/gr-false-friends" = "info"
"asd-ste100/gr-latin-abbrev" = "warn"
"asd-ste100/gr-inclusive-language" = "warn"
"asd-ste100/gr-possessive-form" = "info"
